import { StyleSheet, Dimensions, Keyboard } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  // Common styles
  container: {
    flex: 1,
    backgroundColor: '#2f2f2f',
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#2f2f2f',
  },
  header: {
    padding: 20,
    paddingTop: 100,
    paddingBottom: 30,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: '#fff',
  },
  subtitle: {
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
    opacity: 0.9,
  },
  errorText: {
    fontSize: 18,
    color: '#a0a0a0',
    marginBottom: 20,
  },
  backButton: {
    padding: 16,
    alignItems: 'center',
  },
  backButtonText: {
    color: '#a0a0a0',
    fontSize: 16,
  },
  backButtonBg: {
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 30,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: '#dfaa30',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(155, 155, 155, 0.3)',
    marginVertical: 10,
  },

  // Index screen styles
  safeArea: {
    flex: 1,
    backgroundColor: '#2f2f2f',
  },
  indexContainer: {
    flex: 1,
    backgroundColor: '#2f2f2f',
    padding: 16,
    justifyContent: 'space-between',
  },
  deckGrid: {
    paddingBottom: 20,
  },
  deckCard: {
    flex: 1,
    height: 120,
    margin: 3,
    padding: 5,
    borderRadius: 12,
    justifyContent: 'space-between',
  },
  deckTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    left: 10,
    top: 10,
  },
  addButton: {
    backgroundColor: '#dfaa30',
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
    margin: 20,
  },
  addButtonText: {
    color: '#2f2f2f',
    fontWeight: 'bold',
    fontSize: 30,
  },
  emptyText: {
    textAlign: 'center',
    bottom: '50%',
    marginTop: 40,
    fontSize: 16,
    color: '#888',
  },
  cardCount: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.8,
    left: 10,
    bottom: 10,
  },
  delete: {
    position: 'absolute',
    top: 8,
    right: 8,
    color: '#ff4d4d',
    fontSize: 20,
  },
  fabUnten: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#dfaa30',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
    elevation: 5,
  },
  fabOben: {
    position: 'absolute',
    right: 16,
    bottom: 88,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#dfaa30',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
    elevation: 5,
  },
  hint: {
    fontSize: 14,
    color: '#888',
    marginBottom: 10,
    fontStyle: 'italic',
  },

  // Create screen styles
  createContainer: {
    flex: 1,
    backgroundColor: '#2f2f2f',
    padding: 16,
  },
  form: {
    width: width * 0.9,
    height: height * 0.65,
    transform: [{ perspective: 1000 }],
    backgroundColor: '#1E1E1E',
    padding: 20,
    borderRadius: 12,
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -(width * 0.9) / 2,
    marginTop: -(height * 0.5) / 2,
  },
  label: {
    fontSize: 16,
    marginBottom: 8,
    color: '#D0D0D0',
    margin: 10,
  },
  input: {
    backgroundColor: '#2A2A2A',
    color: '#fff',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 20,
  },
  buttonCreate: {
    backgroundColor: '#dfaa30',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
    width: width * 0.9,
    position: 'absolute',
    bottom: 20,
    left: '50%',
    marginLeft: -(width * 0.9) / 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  buttonText: {
    color: '#2f2f2f',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cancelButton: {
    padding: 16,
    alignItems: 'center',
    marginTop: 10,
  },
  cancelButtonText: {
    color: '#a0a0a0',
    fontSize: 16,
  },
  color: {
    width: 45,
    height: 45,
    borderRadius: 25,
    margin: 5,
    borderWidth: 1,
    borderColor: '#333',
  },
  colorContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 10,
  },

  // Deck screen styles
  startButton: {
    backgroundColor: '#dfaa30',
    margin: 20,
    padding: 16,
    borderRadius: 10,
    alignItems: 'center',
  },
  favIcon: {
    position: 'absolute',
    top: 0,
    right: 10,
    fontSize: 25,
    color: '#dfaa30',
    zIndex: 4,
  },
  favIconButton: {
    position: 'absolute',
    top: 0,
    right: 10,
    fontSize: 30,
    color: '#dfaa30',
    zIndex: 4,
    padding: 20,
  },

  // ListCard styles
  ListCardContainer: {
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    zIndex: 1,
    elevation: 3,
    position: 'relative',
  },
  listQuestion: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'lightgray',
    marginBottom: 8,
  },
  listAnswer: {
    fontSize: 18,
    color: 'green',
    marginBottom: 4,
  },
  listOption: {
    fontSize: 16,
    color: 'lightgray',
    backgroundColor: '#2f2f2f',
    borderRadius: 8,
    padding: 8,
    marginBottom: 4,
  },
  listCorrectAnswer: {
    fontSize: 16,
    color: '#2196F3',
    fontWeight: 'bold',
    marginTop: 8,
  },

  // Modal styles [deckID].tsx & index.tsx
  modalInputDetail: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 9998,
  },
  modalContainerDetail: {
    backgroundColor: '#2f2f2f',
    width: '90%',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    position: 'relative',
    zIndex: 9999,
    elevation: 10,
    top: '-30%',
  },
  searchInputDetail: {
    width: '100%',
    height: 50,
    borderColor: '#888',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#222',
  },
  closeModalDetail: {
    position: 'absolute',
    top: '60%',
    right: '10%',
    zIndex: 10000,
    color: '#aaa',
  },

  modalInputIndex: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 50,
    zIndex: 9998,
  },
  modalContainerIndex: {
    width: '90%',
    backgroundColor: '#2f2f2f',
    borderRadius: 20,
    padding: 20,
    zIndex: 9999,
    top: '-6%',
  },
  searchInputIndex: {
    width: '100%',
    height: 50,
    borderColor: '#888',
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#fff',
    backgroundColor: '#222',
  },
  closeModalIndex: {
    position: 'absolute',
    top: '60%',
    right: '10%',
    zIndex: 10000,
    color: '#aaa',
  },

  // Learn screen styles
  cardContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cardWrapper: {
    width: width * 0.9,
    height: height * 0.5,
    transform: [{ perspective: 1000 }],
  },
  card: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 15,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    backfaceVisibility: 'hidden',
    position: 'absolute',
  },
  cardBack: {
    backgroundColor: '#cccccc',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginBottom: 20,
  },
  cardText: {
    fontSize: 16,
    color: '#555',
    textAlign: 'center',
    lineHeight: 24,
  },
  navigationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    paddingVertical: 15,
  },
  navButton: {
    backgroundColor: '#4a90e2',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  navButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 16,
  },
  disabledButton: {
    backgroundColor: '#cccccc',
    opacity: 0.6,
  },
  learnBackButtonText: {
    color: '#2f2f2f',
    fontWeight: '600',
    fontSize: 16,
  },
  learnErrorText: {
    fontSize: 18,
    color: '#e74c3c',
    marginBottom: 20,
  },
  quizButton: {
    alignSelf: 'center',
    marginTop: 5,
    marginBottom: 5,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: '#dfaa30',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: '70%',
  },
  quizButtonText: {
    color: '#2f2f2f',
    fontWeight: 'bold',
    fontSize: 16,
  },

  // Add Card screen styles
  buttonAdd: {
    backgroundColor: '#dfaa30',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    margin: 10,
  },

// Modal styles
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#2f2f2f',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    width: '80%',
  },
  modalText: {
    marginBottom: 20,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '500',
    color: 'white',
  },
  button: {
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 25,
    elevation: 2,
  },
  buttonClose: {
    backgroundColor: '#dfaa30',
  },
  textStyle: {
    color: '#2f2f2f',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },

  // Edit card screen style
  formEdit: {
    width: width * 0.9,
    height: height * 0.65,
    transform: [{ perspective: 1000 }],
    backgroundColor: '#1E1E1E',
    padding: 20,
    borderRadius: 12,
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -(width * 0.9) / 2,
    marginTop: -(height * 0.5) / 2,
  },

  // import/export styles
  impExpContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
});


export default styles;

